# Generated by Django 5.1.7 on 2025-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_email_remove_appointment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type_of_illness',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
