# Generated by Django 5.1.7 on 2025-05-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_type_of_illness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='type_of_illness',
            new_name='symptoms_of_illness',
        ),
    ]
