# Generated by Django 5.1.7 on 2025-05-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('GENERAL', 'General Checkup'), ('DENTAL', 'Dental'), ('CARDIOLOGY', 'Cardiology')], default='GENERAL', max_length=20),
        ),
    ]
